### ISSUE TITLE
Schedule (system_mode: auto) Mode ?

### ISSUE THREAD

**Issue by phoenix1589** [greeeny101/Hive-Thermostat-Zigbee2MQTT#2]
Hi,

Many thanks for this.

I'm in a slightly unique (crazy?) situation where I want to use the scheduling in the hive thermostat/receiver, and then use HomeAssistant for more immediate control (extra heat now, change target temperature etc).*

I know you say you don't do this; but do you have any experience of how that works? I was expecting system_mode: auto to do this, however setting to auto (from off) did nothing. No heat at the scheduled time and the thermostat reported it was off. 

Setting system_mode: heat (with setpoint_hold: false) seems to put it into schedule mode, with the thermostat reporting SCH which feels wrong and makes me wonder what auto mode actually does?!

* I know most people do away with the Hive scheduling and do it all via Home Assistant (or node-red or whatever). I don't what to do this, as I don't want any issue with the Raspberry Pi etc. to mean the heating doesn't come on.

**Comment by greeeny101** [comment]
I think it's how the hive thermostat works. I just watched what happened in the zigbeet2mqtt logs when I selected schedule on the thermostat and noticed it depends on combinations of system_mode, duration , hold and so on to determine what state to put the thermostat in. That's what this tries to do emulate what payloads get generated when you select something on the thermostat.

In your case the thing that put it into 'schedule' from 'off' was the fact that 'occupied_heating_setpoint' was 1. If you did the same commands when the system was 'heat' then it probably wouldn't do anything

I havent got much experience of this by the way, I've only been messing with this for a couple of weeks

**Comment by phoenix1589** [comment]
> In your case the thing that put it into 'schedule' from 'off' was the fact that 'occupied_heating_setpoint' was 1. If you did the same commands when the system was 'heat' then it probably wouldn't do anything

It's odd logic for that, tho. I think I need to test going from system_mode: off, heating_setpoint: 1, setpoint_hold: false to system_mode: heat, setpoint_hold: true, heating_setpoint: 19 - that I presume won't go into schedule mode and I can see what it does from there.

**Comment by greeeny101** [comment]
You've got me thinking now I'm going to remove the heating setpoint and what difference it makes

**Comment by greeeny101** [comment]
> > In your case the thing that put it into 'schedule' from 'off' was the fact that 'occupied_heating_setpoint' was 1. If you did the same commands when the system was 'heat' then it probably wouldn't do anything
> 
> It's odd logic for that, tho. I think I need to test going from system_mode: off, heating_setpoint: 1, setpoint_hold: false to system_mode: heat, setpoint_hold: true, heating_setpoint: 19 - that I presume won't go into schedule mode and I can see what it does from there.

You were right about setting the `occupied heating setpoint` to 1, it is not required. I've removed it from my config

**Comment by greeeny101** [comment]
I'm looking into this a bit more and found a few things out.

When manual is selected on the thermostat the duration is always 65535.

when selecting the schedule on the thermostat

- System mode is always heat
- hold can be either true or false. Initially it is false. If you change the temperature this will change to true
- duration ** This is the key bit** Initially this will be 0, if you change the temp, it will be updated to the number of minutes remaining until the scheduled section ends.

So if we check that

- `system_mode` == 'heat' and `temperature_setpoint_hold_duration` != 65535  _This is Auto_
- `system_mode` == 'heat' and `temperature_setpoint_hold_duration` == 65535 _This is manual_

Haven't checked what `off` is but im guessing  that system mode is off and hold is always false

**Comment by greeeny101** [comment]
@phoenix1589  I've updated this so that the schedule set in the thermostat is replicated in the heating component. Hopefully this is what you were after. My original plan was to use a schedule in HA but I've not got anywhere near doing that yet so for the moment its probably more important to get the component doing the same as the thermostat. Once that's working then I'll maybe add a switch or something so there's the ability to use either the built in schedule or a HA provided one

**Comment by phoenix1589** [comment]
@greeeny101 thanks! I'm a bit tied up but will have a few hours to play with this on Saturday
