### ISSUE TITLE
Water Schedule mode inoperative

### ISSUE THREAD

**Issue by cmewse2** [greeeny101/Hive-Thermostat-Zigbee2MQTT#9]
Using the simple climate card I can set water to OFF or ON but the schedule button does nothing for some reason, checked yaml and card config. Any ideas?

z2mqtt logs:

Water button:
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/heating', payload..... "system_mode_water":"heat"

schedule button press:
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/heating', payload..... "system_mode_water":"auto"

Off button:
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/heating', payload..... "system_mode_water":"off"

is "auto" the correct MQTT mode to transmit?

**Comment by greeeny101** [comment]
Hi,

Unfortunately I never managed to get round to implementing the schedule button. My plan was to use a scheduler in HA and make the existing component either ignore scheduler input to turn on/off the thermostat based upon the state of the schedule button.

**Comment by cmewse2** [comment]
No worries, i have switched over to this solution: [https://github.com/andrew-codechimp/HA-Hive-Local-Thermostat](url)

**Comment by greeeny101** [comment]
Yeah that makes more sense as an integration hides all the inner workings of my solution
